import axios from "axios";
import {
  GET_DATA_REQUEST,
  GET_DATA_SUCCESS,
  GET_DATA_FAILURE,
  GO_TO_FORECAST,
  BACK_TO_CURRENT,
  SHOW_SEARCH_BOX,
  HIDE_SEARCH_BOX,
} from "./types";

const initialState = {
  response: {
    location: {
      name: "London",
      region: "City of London, Greater London",
      country: "United Kingdom",
      lat: 51.52,
      lon: -0.11,
      tz_id: "Europe/London",
      localtime_epoch: 1652998023,
      localtime: "2022-05-19 23:07",
    },
    current: {
      last_updated_epoch: 1652994000,
      last_updated: "2022-05-19 22:00",
      temp_c: 16.0,
      temp_f: 60.8,
      is_day: 0,
      condition: {
        text: "Clear",
        icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
        code: 1000,
      },
      wind_mph: 10.5,
      wind_kph: 16.9,
      wind_degree: 220,
      wind_dir: "SW",
      pressure_mb: 1020.0,
      pressure_in: 30.12,
      precip_mm: 0.0,
      precip_in: 0.0,
      humidity: 55,
      cloud: 0,
      feelslike_c: 16.0,
      feelslike_f: 60.8,
      vis_km: 10.0,
      vis_miles: 6.0,
      uv: 1.0,
      gust_mph: 8.3,
      gust_kph: 13.3,
      air_quality: {
        co: 243.6999969482422,
        no2: 35.29999923706055,
        o3: 36.099998474121094,
        so2: 10.699999809265137,
        pm2_5: 5.599999904632568,
        pm10: 8.199999809265137,
        "us-epa-index": 1,
        "gb-defra-index": 1,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2022-05-19",
          date_epoch: 1652918400,
          day: {
            maxtemp_c: 22.5,
            maxtemp_f: 72.5,
            mintemp_c: 13.4,
            mintemp_f: 56.1,
            avgtemp_c: 17.2,
            avgtemp_f: 62.9,
            maxwind_mph: 8.7,
            maxwind_kph: 14.0,
            totalprecip_mm: 7.9,
            totalprecip_in: 0.31,
            avgvis_km: 9.5,
            avgvis_miles: 5.0,
            avghumidity: 70.0,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 86,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            uv: 6.0,
          },
          astro: {
            sunrise: "05:03 AM",
            sunset: "08:52 PM",
            moonrise: "12:26 AM",
            moonset: "07:24 AM",
            moon_phase: "Waning Gibbous",
            moon_illumination: "71",
          },
          hour: [
            {
              time_epoch: 1652914800,
              time: "2022-05-19 00:00",
              temp_c: 15.7,
              temp_f: 60.3,
              is_day: 0,
              condition: {
                text: "Fog",
                icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
                code: 1135,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 217,
              wind_dir: "SW",
              pressure_mb: 1015.0,
              pressure_in: 29.97,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 98,
              cloud: 100,
              feelslike_c: 15.7,
              feelslike_f: 60.3,
              windchill_c: 15.7,
              windchill_f: 60.3,
              heatindex_c: 15.7,
              heatindex_f: 60.3,
              dewpoint_c: 15.4,
              dewpoint_f: 59.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 0.0,
              vis_miles: 0.0,
              gust_mph: 6.7,
              gust_kph: 10.8,
              uv: 1.0,
            },
            {
              time_epoch: 1652918400,
              time: "2022-05-19 01:00",
              temp_c: 15.4,
              temp_f: 59.7,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 269,
              wind_dir: "W",
              pressure_mb: 1014.0,
              pressure_in: 29.96,
              precip_mm: 1.7,
              precip_in: 0.07,
              humidity: 97,
              cloud: 100,
              feelslike_c: 15.4,
              feelslike_f: 59.7,
              windchill_c: 15.4,
              windchill_f: 59.7,
              heatindex_c: 15.4,
              heatindex_f: 59.7,
              dewpoint_c: 15.0,
              dewpoint_f: 59.0,
              will_it_rain: 0,
              chance_of_rain: 50,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 1.0,
            },
            {
              time_epoch: 1652922000,
              time: "2022-05-19 02:00",
              temp_c: 15.0,
              temp_f: 59.0,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 280,
              wind_dir: "W",
              pressure_mb: 1015.0,
              pressure_in: 29.96,
              precip_mm: 0.7,
              precip_in: 0.03,
              humidity: 96,
              cloud: 100,
              feelslike_c: 14.9,
              feelslike_f: 58.8,
              windchill_c: 14.9,
              windchill_f: 58.8,
              heatindex_c: 15.0,
              heatindex_f: 59.0,
              dewpoint_c: 14.4,
              dewpoint_f: 57.9,
              will_it_rain: 0,
              chance_of_rain: 68,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.9,
              gust_kph: 11.2,
              uv: 1.0,
            },
            {
              time_epoch: 1652925600,
              time: "2022-05-19 03:00",
              temp_c: 14.8,
              temp_f: 58.6,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 278,
              wind_dir: "W",
              pressure_mb: 1015.0,
              pressure_in: 29.97,
              precip_mm: 2.5,
              precip_in: 0.1,
              humidity: 97,
              cloud: 76,
              feelslike_c: 14.7,
              feelslike_f: 58.5,
              windchill_c: 14.7,
              windchill_f: 58.5,
              heatindex_c: 14.8,
              heatindex_f: 58.6,
              dewpoint_c: 14.2,
              dewpoint_f: 57.6,
              will_it_rain: 0,
              chance_of_rain: 62,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.9,
              gust_kph: 11.2,
              uv: 1.0,
            },
            {
              time_epoch: 1652929200,
              time: "2022-05-19 04:00",
              temp_c: 13.9,
              temp_f: 57.0,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 6.0,
              wind_kph: 9.7,
              wind_degree: 276,
              wind_dir: "W",
              pressure_mb: 1016.0,
              pressure_in: 29.99,
              precip_mm: 0.5,
              precip_in: 0.02,
              humidity: 97,
              cloud: 61,
              feelslike_c: 13.3,
              feelslike_f: 55.9,
              windchill_c: 13.3,
              windchill_f: 55.9,
              heatindex_c: 13.9,
              heatindex_f: 57.0,
              dewpoint_c: 13.3,
              dewpoint_f: 55.9,
              will_it_rain: 1,
              chance_of_rain: 86,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 1.0,
            },
            {
              time_epoch: 1652932800,
              time: "2022-05-19 05:00",
              temp_c: 13.4,
              temp_f: 56.1,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 284,
              wind_dir: "WNW",
              pressure_mb: 1016.0,
              pressure_in: 30.0,
              precip_mm: 0.5,
              precip_in: 0.02,
              humidity: 96,
              cloud: 63,
              feelslike_c: 12.7,
              feelslike_f: 54.9,
              windchill_c: 12.7,
              windchill_f: 54.9,
              heatindex_c: 13.4,
              heatindex_f: 56.1,
              dewpoint_c: 12.7,
              dewpoint_f: 54.9,
              will_it_rain: 1,
              chance_of_rain: 74,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 1.0,
            },
            {
              time_epoch: 1652936400,
              time: "2022-05-19 06:00",
              temp_c: 13.6,
              temp_f: 56.5,
              is_day: 1,
              condition: {
                text: "Patchy light rain",
                icon: "//cdn.weatherapi.com/weather/64x64/day/293.png",
                code: 1180,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 286,
              wind_dir: "WNW",
              pressure_mb: 1017.0,
              pressure_in: 30.03,
              precip_mm: 2.0,
              precip_in: 0.08,
              humidity: 93,
              cloud: 57,
              feelslike_c: 12.8,
              feelslike_f: 55.0,
              windchill_c: 12.8,
              windchill_f: 55.0,
              heatindex_c: 13.6,
              heatindex_f: 56.5,
              dewpoint_c: 12.4,
              dewpoint_f: 54.3,
              will_it_rain: 1,
              chance_of_rain: 81,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9.0,
              vis_miles: 5.0,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 3.0,
            },
            {
              time_epoch: 1652940000,
              time: "2022-05-19 07:00",
              temp_c: 14.0,
              temp_f: 57.2,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 287,
              wind_dir: "WNW",
              pressure_mb: 1018.0,
              pressure_in: 30.05,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 87,
              cloud: 38,
              feelslike_c: 13.3,
              feelslike_f: 55.9,
              windchill_c: 13.3,
              windchill_f: 55.9,
              heatindex_c: 14.0,
              heatindex_f: 57.2,
              dewpoint_c: 11.9,
              dewpoint_f: 53.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 4.0,
            },
            {
              time_epoch: 1652943600,
              time: "2022-05-19 08:00",
              temp_c: 14.9,
              temp_f: 58.8,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 277,
              wind_dir: "W",
              pressure_mb: 1018.0,
              pressure_in: 30.06,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 79,
              cloud: 60,
              feelslike_c: 14.4,
              feelslike_f: 57.9,
              windchill_c: 14.4,
              windchill_f: 57.9,
              heatindex_c: 14.9,
              heatindex_f: 58.8,
              dewpoint_c: 11.2,
              dewpoint_f: 52.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.8,
              gust_kph: 12.6,
              uv: 4.0,
            },
            {
              time_epoch: 1652947200,
              time: "2022-05-19 09:00",
              temp_c: 15.6,
              temp_f: 60.1,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 268,
              wind_dir: "W",
              pressure_mb: 1018.0,
              pressure_in: 30.07,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 78,
              cloud: 57,
              feelslike_c: 15.6,
              feelslike_f: 60.1,
              windchill_c: 15.6,
              windchill_f: 60.1,
              heatindex_c: 15.6,
              heatindex_f: 60.1,
              dewpoint_c: 11.8,
              dewpoint_f: 53.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.1,
              gust_kph: 13.0,
              uv: 5.0,
            },
            {
              time_epoch: 1652950800,
              time: "2022-05-19 10:00",
              temp_c: 17.9,
              temp_f: 64.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 268,
              wind_dir: "W",
              pressure_mb: 1018.0,
              pressure_in: 30.07,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 57,
              cloud: 6,
              feelslike_c: 17.9,
              feelslike_f: 64.2,
              windchill_c: 17.9,
              windchill_f: 64.2,
              heatindex_c: 17.9,
              heatindex_f: 64.2,
              dewpoint_c: 9.3,
              dewpoint_f: 48.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.1,
              gust_kph: 13.0,
              uv: 5.0,
            },
            {
              time_epoch: 1652954400,
              time: "2022-05-19 11:00",
              temp_c: 19.9,
              temp_f: 67.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 271,
              wind_dir: "W",
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 48,
              cloud: 3,
              feelslike_c: 19.9,
              feelslike_f: 67.8,
              windchill_c: 19.9,
              windchill_f: 67.8,
              heatindex_c: 19.9,
              heatindex_f: 67.8,
              dewpoint_c: 8.7,
              dewpoint_f: 47.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 5.0,
            },
            {
              time_epoch: 1652958000,
              time: "2022-05-19 12:00",
              temp_c: 21.5,
              temp_f: 70.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.1,
              wind_kph: 13.0,
              wind_degree: 266,
              wind_dir: "W",
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 44,
              cloud: 0,
              feelslike_c: 21.5,
              feelslike_f: 70.7,
              windchill_c: 21.5,
              windchill_f: 70.7,
              heatindex_c: 24.1,
              heatindex_f: 75.4,
              dewpoint_c: 8.8,
              dewpoint_f: 47.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 6.0,
            },
            {
              time_epoch: 1652961600,
              time: "2022-05-19 13:00",
              temp_c: 22.0,
              temp_f: 71.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14.0,
              wind_degree: 261,
              wind_dir: "W",
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 42,
              cloud: 0,
              feelslike_c: 24.1,
              feelslike_f: 75.4,
              windchill_c: 22.0,
              windchill_f: 71.6,
              heatindex_c: 24.1,
              heatindex_f: 75.4,
              dewpoint_c: 8.5,
              dewpoint_f: 47.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 6.0,
            },
            {
              time_epoch: 1652965200,
              time: "2022-05-19 14:00",
              temp_c: 21.0,
              temp_f: 69.8,
              is_day: 1,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                code: 1006,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 257,
              wind_dir: "WSW",
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 41,
              cloud: 79,
              feelslike_c: 21.0,
              feelslike_f: 69.8,
              windchill_c: 21.0,
              windchill_f: 69.8,
              heatindex_c: 21.0,
              heatindex_f: 69.8,
              dewpoint_c: 7.3,
              dewpoint_f: 45.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 5.0,
            },
            {
              time_epoch: 1652968800,
              time: "2022-05-19 15:00",
              temp_c: 22.5,
              temp_f: 72.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 259,
              wind_dir: "W",
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 42,
              cloud: 2,
              feelslike_c: 24.2,
              feelslike_f: 75.6,
              windchill_c: 22.5,
              windchill_f: 72.5,
              heatindex_c: 24.2,
              heatindex_f: 75.6,
              dewpoint_c: 8.9,
              dewpoint_f: 48.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 6.0,
            },
            {
              time_epoch: 1652972400,
              time: "2022-05-19 16:00",
              temp_c: 21.2,
              temp_f: 70.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.1,
              wind_kph: 13.0,
              wind_degree: 253,
              wind_dir: "WSW",
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 43,
              cloud: 8,
              feelslike_c: 21.2,
              feelslike_f: 70.2,
              windchill_c: 21.2,
              windchill_f: 70.2,
              heatindex_c: 24.0,
              heatindex_f: 75.2,
              dewpoint_c: 8.1,
              dewpoint_f: 46.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 6.0,
            },
            {
              time_epoch: 1652976000,
              time: "2022-05-19 17:00",
              temp_c: 20.4,
              temp_f: 68.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 250,
              wind_dir: "WSW",
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 45,
              cloud: 21,
              feelslike_c: 20.4,
              feelslike_f: 68.7,
              windchill_c: 20.4,
              windchill_f: 68.7,
              heatindex_c: 20.4,
              heatindex_f: 68.7,
              dewpoint_c: 8.2,
              dewpoint_f: 46.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.7,
              gust_kph: 14.0,
              uv: 6.0,
            },
            {
              time_epoch: 1652979600,
              time: "2022-05-19 18:00",
              temp_c: 19.8,
              temp_f: 67.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 240,
              wind_dir: "WSW",
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 52,
              cloud: 16,
              feelslike_c: 19.8,
              feelslike_f: 67.6,
              windchill_c: 19.8,
              windchill_f: 67.6,
              heatindex_c: 19.8,
              heatindex_f: 67.6,
              dewpoint_c: 9.7,
              dewpoint_f: 49.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.4,
              gust_kph: 11.9,
              uv: 5.0,
            },
            {
              time_epoch: 1652983200,
              time: "2022-05-19 19:00",
              temp_c: 19.6,
              temp_f: 67.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 226,
              wind_dir: "SW",
              pressure_mb: 1020.0,
              pressure_in: 30.11,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 61,
              cloud: 3,
              feelslike_c: 19.6,
              feelslike_f: 67.3,
              windchill_c: 19.6,
              windchill_f: 67.3,
              heatindex_c: 19.6,
              heatindex_f: 67.3,
              dewpoint_c: 12.0,
              dewpoint_f: 53.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 5.0,
            },
            {
              time_epoch: 1652986800,
              time: "2022-05-19 20:00",
              temp_c: 15.6,
              temp_f: 60.1,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 207,
              wind_dir: "SSW",
              pressure_mb: 1020.0,
              pressure_in: 30.13,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 70,
              cloud: 30,
              feelslike_c: 15.6,
              feelslike_f: 60.1,
              windchill_c: 15.6,
              windchill_f: 60.1,
              heatindex_c: 15.6,
              heatindex_f: 60.1,
              dewpoint_c: 10.1,
              dewpoint_f: 50.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.3,
              gust_kph: 13.3,
              uv: 5.0,
            },
            {
              time_epoch: 1652990400,
              time: "2022-05-19 21:00",
              temp_c: 14.8,
              temp_f: 58.6,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 5.6,
              wind_kph: 9.0,
              wind_degree: 219,
              wind_dir: "SW",
              pressure_mb: 1021.0,
              pressure_in: 30.15,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 73,
              cloud: 97,
              feelslike_c: 14.5,
              feelslike_f: 58.1,
              windchill_c: 14.5,
              windchill_f: 58.1,
              heatindex_c: 14.8,
              heatindex_f: 58.6,
              dewpoint_c: 10.1,
              dewpoint_f: 50.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.7,
              gust_kph: 14.0,
              uv: 1.0,
            },
            {
              time_epoch: 1652994000,
              time: "2022-05-19 22:00",
              temp_c: 14.6,
              temp_f: 58.3,
              is_day: 0,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 5.6,
              wind_kph: 9.0,
              wind_degree: 224,
              wind_dir: "SW",
              pressure_mb: 1021.0,
              pressure_in: 30.14,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 74,
              cloud: 64,
              feelslike_c: 14.3,
              feelslike_f: 57.7,
              windchill_c: 14.3,
              windchill_f: 57.7,
              heatindex_c: 14.6,
              heatindex_f: 58.3,
              dewpoint_c: 10.0,
              dewpoint_f: 50.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.3,
              gust_kph: 13.3,
              uv: 1.0,
            },
            {
              time_epoch: 1652997600,
              time: "2022-05-19 23:00",
              temp_c: 14.5,
              temp_f: 58.1,
              is_day: 0,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 4.0,
              wind_kph: 6.5,
              wind_degree: 220,
              wind_dir: "SW",
              pressure_mb: 1020.0,
              pressure_in: 30.13,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 75,
              cloud: 69,
              feelslike_c: 14.6,
              feelslike_f: 58.3,
              windchill_c: 14.6,
              windchill_f: 58.3,
              heatindex_c: 14.5,
              heatindex_f: 58.1,
              dewpoint_c: 10.1,
              dewpoint_f: 50.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.6,
              gust_kph: 9.0,
              uv: 1.0,
            },
          ],
        },
        {
          date: "2022-05-20",
          date_epoch: 1653004800,
          day: {
            maxtemp_c: 16.6,
            maxtemp_f: 61.9,
            mintemp_c: 11.6,
            mintemp_f: 52.9,
            avgtemp_c: 13.6,
            avgtemp_f: 56.5,
            maxwind_mph: 10.7,
            maxwind_kph: 17.3,
            totalprecip_mm: 1.2,
            totalprecip_in: 0.05,
            avgvis_km: 9.7,
            avgvis_miles: 6.0,
            avghumidity: 77.0,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 90,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 2.0,
          },
          astro: {
            sunrise: "05:02 AM",
            sunset: "08:53 PM",
            moonrise: "01:23 AM",
            moonset: "08:40 AM",
            moon_phase: "Waning Gibbous",
            moon_illumination: "64",
          },
          hour: [
            {
              time_epoch: 1653001200,
              time: "2022-05-20 00:00",
              temp_c: 14.0,
              temp_f: 57.2,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 217,
              wind_dir: "SW",
              pressure_mb: 1021.0,
              pressure_in: 30.14,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 50,
              feelslike_c: 13.8,
              feelslike_f: 56.8,
              windchill_c: 13.8,
              windchill_f: 56.8,
              heatindex_c: 14.0,
              heatindex_f: 57.2,
              dewpoint_c: 9.8,
              dewpoint_f: 49.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.7,
              gust_kph: 10.8,
              uv: 1.0,
            },
            {
              time_epoch: 1653004800,
              time: "2022-05-20 01:00",
              temp_c: 13.4,
              temp_f: 56.1,
              is_day: 0,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 215,
              wind_dir: "SW",
              pressure_mb: 1020.0,
              pressure_in: 30.13,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 77,
              cloud: 77,
              feelslike_c: 13.2,
              feelslike_f: 55.8,
              windchill_c: 13.2,
              windchill_f: 55.8,
              heatindex_c: 13.4,
              heatindex_f: 56.1,
              dewpoint_c: 9.5,
              dewpoint_f: 49.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.7,
              gust_kph: 10.8,
              uv: 1.0,
            },
            {
              time_epoch: 1653008400,
              time: "2022-05-20 02:00",
              temp_c: 13.4,
              temp_f: 56.1,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 220,
              wind_dir: "SW",
              pressure_mb: 1020.0,
              pressure_in: 30.12,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 45,
              feelslike_c: 13.3,
              feelslike_f: 55.9,
              windchill_c: 13.3,
              windchill_f: 55.9,
              heatindex_c: 13.4,
              heatindex_f: 56.1,
              dewpoint_c: 9.2,
              dewpoint_f: 48.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.6,
              gust_kph: 9.0,
              uv: 1.0,
            },
            {
              time_epoch: 1653012000,
              time: "2022-05-20 03:00",
              temp_c: 12.9,
              temp_f: 55.2,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 242,
              wind_dir: "WSW",
              pressure_mb: 1020.0,
              pressure_in: 30.12,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 90,
              feelslike_c: 12.6,
              feelslike_f: 54.7,
              windchill_c: 12.6,
              windchill_f: 54.7,
              heatindex_c: 12.9,
              heatindex_f: 55.2,
              dewpoint_c: 8.7,
              dewpoint_f: 47.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 1.0,
            },
            {
              time_epoch: 1653015600,
              time: "2022-05-20 04:00",
              temp_c: 12.4,
              temp_f: 54.3,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 4.0,
              wind_kph: 6.5,
              wind_degree: 235,
              wind_dir: "SW",
              pressure_mb: 1020.0,
              pressure_in: 30.12,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 53,
              feelslike_c: 12.1,
              feelslike_f: 53.8,
              windchill_c: 12.1,
              windchill_f: 53.8,
              heatindex_c: 12.4,
              heatindex_f: 54.3,
              dewpoint_c: 8.2,
              dewpoint_f: 46.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.3,
              gust_kph: 10.1,
              uv: 1.0,
            },
            {
              time_epoch: 1653019200,
              time: "2022-05-20 05:00",
              temp_c: 12.7,
              temp_f: 54.9,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 4.0,
              wind_kph: 6.5,
              wind_degree: 237,
              wind_dir: "WSW",
              pressure_mb: 1020.0,
              pressure_in: 30.11,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 73,
              cloud: 48,
              feelslike_c: 12.5,
              feelslike_f: 54.5,
              windchill_c: 12.5,
              windchill_f: 54.5,
              heatindex_c: 12.7,
              heatindex_f: 54.9,
              dewpoint_c: 7.9,
              dewpoint_f: 46.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.8,
              gust_kph: 9.4,
              uv: 1.0,
            },
            {
              time_epoch: 1653022800,
              time: "2022-05-20 06:00",
              temp_c: 13.4,
              temp_f: 56.1,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 243,
              wind_dir: "WSW",
              pressure_mb: 1020.0,
              pressure_in: 30.11,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 68,
              cloud: 47,
              feelslike_c: 13.1,
              feelslike_f: 55.6,
              windchill_c: 13.1,
              windchill_f: 55.6,
              heatindex_c: 13.4,
              heatindex_f: 56.1,
              dewpoint_c: 7.6,
              dewpoint_f: 45.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.0,
              gust_kph: 9.7,
              uv: 4.0,
            },
            {
              time_epoch: 1653026400,
              time: "2022-05-20 07:00",
              temp_c: 14.0,
              temp_f: 57.2,
              is_day: 1,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                code: 1006,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 242,
              wind_dir: "WSW",
              pressure_mb: 1019.0,
              pressure_in: 30.1,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 63,
              cloud: 65,
              feelslike_c: 13.8,
              feelslike_f: 56.8,
              windchill_c: 13.8,
              windchill_f: 56.8,
              heatindex_c: 14.0,
              heatindex_f: 57.2,
              dewpoint_c: 7.0,
              dewpoint_f: 44.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.8,
              gust_kph: 9.4,
              uv: 3.0,
            },
            {
              time_epoch: 1653030000,
              time: "2022-05-20 08:00",
              temp_c: 15.0,
              temp_f: 59.0,
              is_day: 1,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                code: 1006,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 255,
              wind_dir: "WSW",
              pressure_mb: 1019.0,
              pressure_in: 30.1,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 56,
              cloud: 64,
              feelslike_c: 14.9,
              feelslike_f: 58.8,
              windchill_c: 14.9,
              windchill_f: 58.8,
              heatindex_c: 15.0,
              heatindex_f: 59.0,
              dewpoint_c: 6.4,
              dewpoint_f: 43.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.0,
              gust_kph: 9.7,
              uv: 4.0,
            },
            {
              time_epoch: 1653033600,
              time: "2022-05-20 09:00",
              temp_c: 15.4,
              temp_f: 59.7,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 6.0,
              wind_kph: 9.7,
              wind_degree: 267,
              wind_dir: "W",
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 56,
              cloud: 48,
              feelslike_c: 15.4,
              feelslike_f: 59.7,
              windchill_c: 15.4,
              windchill_f: 59.7,
              heatindex_c: 15.4,
              heatindex_f: 59.7,
              dewpoint_c: 6.6,
              dewpoint_f: 43.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 5.0,
            },
            {
              time_epoch: 1653037200,
              time: "2022-05-20 10:00",
              temp_c: 13.5,
              temp_f: 56.3,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 272,
              wind_dir: "W",
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 73,
              cloud: 100,
              feelslike_c: 12.5,
              feelslike_f: 54.5,
              windchill_c: 12.5,
              windchill_f: 54.5,
              heatindex_c: 13.5,
              heatindex_f: 56.3,
              dewpoint_c: 8.8,
              dewpoint_f: 47.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 3.0,
            },
            {
              time_epoch: 1653040800,
              time: "2022-05-20 11:00",
              temp_c: 11.8,
              temp_f: 53.2,
              is_day: 1,
              condition: {
                text: "Light drizzle",
                icon: "//cdn.weatherapi.com/weather/64x64/day/266.png",
                code: 1153,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 269,
              wind_dir: "W",
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.4,
              precip_in: 0.02,
              humidity: 90,
              cloud: 100,
              feelslike_c: 10.8,
              feelslike_f: 51.4,
              windchill_c: 10.8,
              windchill_f: 51.4,
              heatindex_c: 11.8,
              heatindex_f: 53.2,
              dewpoint_c: 10.2,
              dewpoint_f: 50.4,
              will_it_rain: 1,
              chance_of_rain: 90,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2.0,
              vis_miles: 1.0,
              gust_mph: 8.1,
              gust_kph: 13.0,
              uv: 3.0,
            },
            {
              time_epoch: 1653044400,
              time: "2022-05-20 12:00",
              temp_c: 11.6,
              temp_f: 52.9,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 246,
              wind_dir: "WSW",
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 90,
              cloud: 100,
              feelslike_c: 11.1,
              feelslike_f: 52.0,
              windchill_c: 11.1,
              windchill_f: 52.0,
              heatindex_c: 11.6,
              heatindex_f: 52.9,
              dewpoint_c: 10.0,
              dewpoint_f: 50.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.6,
              gust_kph: 9.0,
              uv: 3.0,
            },
            {
              time_epoch: 1653048000,
              time: "2022-05-20 13:00",
              temp_c: 11.9,
              temp_f: 53.4,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 5.6,
              wind_kph: 9.0,
              wind_degree: 233,
              wind_dir: "SW",
              pressure_mb: 1018.0,
              pressure_in: 30.07,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 89,
              cloud: 100,
              feelslike_c: 11.1,
              feelslike_f: 52.0,
              windchill_c: 11.1,
              windchill_f: 52.0,
              heatindex_c: 11.9,
              heatindex_f: 53.4,
              dewpoint_c: 10.2,
              dewpoint_f: 50.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 3.0,
            },
            {
              time_epoch: 1653051600,
              time: "2022-05-20 14:00",
              temp_c: 14.2,
              temp_f: 57.6,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 242,
              wind_dir: "WSW",
              pressure_mb: 1018.0,
              pressure_in: 30.06,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 75,
              cloud: 35,
              feelslike_c: 13.4,
              feelslike_f: 56.1,
              windchill_c: 13.4,
              windchill_f: 56.1,
              heatindex_c: 14.2,
              heatindex_f: 57.6,
              dewpoint_c: 9.8,
              dewpoint_f: 49.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.7,
              gust_kph: 14.0,
              uv: 4.0,
            },
            {
              time_epoch: 1653055200,
              time: "2022-05-20 15:00",
              temp_c: 16.6,
              temp_f: 61.9,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 9.2,
              wind_kph: 14.8,
              wind_degree: 247,
              wind_dir: "WSW",
              pressure_mb: 1018.0,
              pressure_in: 30.05,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 61,
              cloud: 100,
              feelslike_c: 16.6,
              feelslike_f: 61.9,
              windchill_c: 16.6,
              windchill_f: 61.9,
              heatindex_c: 16.6,
              heatindex_f: 61.9,
              dewpoint_c: 9.1,
              dewpoint_f: 48.4,
              will_it_rain: 0,
              chance_of_rain: 70,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.5,
              gust_kph: 16.9,
              uv: 4.0,
            },
            {
              time_epoch: 1653058800,
              time: "2022-05-20 16:00",
              temp_c: 15.6,
              temp_f: 60.1,
              is_day: 1,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                code: 1006,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 252,
              wind_dir: "WSW",
              pressure_mb: 1018.0,
              pressure_in: 30.05,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 71,
              cloud: 64,
              feelslike_c: 15.6,
              feelslike_f: 60.1,
              windchill_c: 15.6,
              windchill_f: 60.1,
              heatindex_c: 15.6,
              heatindex_f: 60.1,
              dewpoint_c: 10.3,
              dewpoint_f: 50.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 12.5,
              gust_kph: 20.2,
              uv: 4.0,
            },
            {
              time_epoch: 1653062400,
              time: "2022-05-20 17:00",
              temp_c: 16.3,
              temp_f: 61.3,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 247,
              wind_dir: "WSW",
              pressure_mb: 1018.0,
              pressure_in: 30.06,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 67,
              cloud: 78,
              feelslike_c: 16.3,
              feelslike_f: 61.3,
              windchill_c: 16.3,
              windchill_f: 61.3,
              heatindex_c: 16.3,
              heatindex_f: 61.3,
              dewpoint_c: 10.3,
              dewpoint_f: 50.5,
              will_it_rain: 1,
              chance_of_rain: 86,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 13.0,
              gust_kph: 20.9,
              uv: 4.0,
            },
            {
              time_epoch: 1653066000,
              time: "2022-05-20 18:00",
              temp_c: 15.3,
              temp_f: 59.5,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 235,
              wind_dir: "SW",
              pressure_mb: 1018.0,
              pressure_in: 30.06,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 78,
              cloud: 51,
              feelslike_c: 15.3,
              feelslike_f: 59.5,
              windchill_c: 15.3,
              windchill_f: 59.5,
              heatindex_c: 15.3,
              heatindex_f: 59.5,
              dewpoint_c: 11.5,
              dewpoint_f: 52.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 13.4,
              gust_kph: 21.6,
              uv: 5.0,
            },
            {
              time_epoch: 1653069600,
              time: "2022-05-20 19:00",
              temp_c: 13.8,
              temp_f: 56.8,
              is_day: 1,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
                code: 1240,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 230,
              wind_dir: "SW",
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.2,
              precip_in: 0.01,
              humidity: 87,
              cloud: 67,
              feelslike_c: 12.4,
              feelslike_f: 54.3,
              windchill_c: 12.4,
              windchill_f: 54.3,
              heatindex_c: 13.8,
              heatindex_f: 56.8,
              dewpoint_c: 11.7,
              dewpoint_f: 53.1,
              will_it_rain: 0,
              chance_of_rain: 66,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 16.6,
              gust_kph: 26.6,
              uv: 3.0,
            },
            {
              time_epoch: 1653073200,
              time: "2022-05-20 20:00",
              temp_c: 12.8,
              temp_f: 55.0,
              is_day: 1,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                code: 1006,
              },
              wind_mph: 10.5,
              wind_kph: 16.9,
              wind_degree: 230,
              wind_dir: "SW",
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 91,
              cloud: 65,
              feelslike_c: 11.2,
              feelslike_f: 52.2,
              windchill_c: 11.2,
              windchill_f: 52.2,
              heatindex_c: 12.8,
              heatindex_f: 55.0,
              dewpoint_c: 11.4,
              dewpoint_f: 52.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 17.2,
              gust_kph: 27.7,
              uv: 3.0,
            },
            {
              time_epoch: 1653076800,
              time: "2022-05-20 21:00",
              temp_c: 12.4,
              temp_f: 54.3,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 232,
              wind_dir: "SW",
              pressure_mb: 1019.0,
              pressure_in: 30.1,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 93,
              cloud: 60,
              feelslike_c: 10.7,
              feelslike_f: 51.3,
              windchill_c: 10.7,
              windchill_f: 51.3,
              heatindex_c: 12.4,
              heatindex_f: 54.3,
              dewpoint_c: 11.4,
              dewpoint_f: 52.5,
              will_it_rain: 0,
              chance_of_rain: 69,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 17.0,
              gust_kph: 27.4,
              uv: 1.0,
            },
            {
              time_epoch: 1653080400,
              time: "2022-05-20 22:00",
              temp_c: 12.1,
              temp_f: 53.8,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 235,
              wind_dir: "SW",
              pressure_mb: 1020.0,
              pressure_in: 30.11,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 95,
              cloud: 58,
              feelslike_c: 10.3,
              feelslike_f: 50.5,
              windchill_c: 10.3,
              windchill_f: 50.5,
              heatindex_c: 12.1,
              heatindex_f: 53.8,
              dewpoint_c: 11.3,
              dewpoint_f: 52.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 1.0,
            },
            {
              time_epoch: 1653084000,
              time: "2022-05-20 23:00",
              temp_c: 12.0,
              temp_f: 53.6,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 10.5,
              wind_kph: 16.9,
              wind_degree: 243,
              wind_dir: "WSW",
              pressure_mb: 1020.0,
              pressure_in: 30.12,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 94,
              cloud: 88,
              feelslike_c: 10.2,
              feelslike_f: 50.4,
              windchill_c: 10.2,
              windchill_f: 50.4,
              heatindex_c: 12.0,
              heatindex_f: 53.6,
              dewpoint_c: 11.0,
              dewpoint_f: 51.8,
              will_it_rain: 0,
              chance_of_rain: 66,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 16.3,
              gust_kph: 26.3,
              uv: 1.0,
            },
          ],
        },
        {
          date: "2022-05-21",
          date_epoch: 1653091200,
          day: {
            maxtemp_c: 19.1,
            maxtemp_f: 66.4,
            mintemp_c: 9.5,
            mintemp_f: 49.1,
            avgtemp_c: 14.3,
            avgtemp_f: 57.8,
            maxwind_mph: 9.6,
            maxwind_kph: 15.5,
            totalprecip_mm: 0.0,
            totalprecip_in: 0.0,
            avgvis_km: 10.0,
            avgvis_miles: 6.0,
            avghumidity: 69.0,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            uv: 5.0,
          },
          astro: {
            sunrise: "05:01 AM",
            sunset: "08:55 PM",
            moonrise: "02:03 AM",
            moonset: "10:04 AM",
            moon_phase: "Waning Gibbous",
            moon_illumination: "57",
          },
          hour: [
            {
              time_epoch: 1653087600,
              time: "2022-05-21 00:00",
              temp_c: 11.6,
              temp_f: 52.9,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 249,
              wind_dir: "WSW",
              pressure_mb: 1020.0,
              pressure_in: 30.13,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 93,
              cloud: 31,
              feelslike_c: 9.8,
              feelslike_f: 49.6,
              windchill_c: 9.8,
              windchill_f: 49.6,
              heatindex_c: 11.6,
              heatindex_f: 52.9,
              dewpoint_c: 10.4,
              dewpoint_f: 50.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.0,
              gust_kph: 24.1,
              uv: 1.0,
            },
            {
              time_epoch: 1653091200,
              time: "2022-05-21 01:00",
              temp_c: 11.0,
              temp_f: 51.8,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 249,
              wind_dir: "WSW",
              pressure_mb: 1020.0,
              pressure_in: 30.13,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 92,
              cloud: 39,
              feelslike_c: 9.1,
              feelslike_f: 48.4,
              windchill_c: 9.1,
              windchill_f: 48.4,
              heatindex_c: 11.0,
              heatindex_f: 51.8,
              dewpoint_c: 9.8,
              dewpoint_f: 49.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 14.8,
              gust_kph: 23.8,
              uv: 1.0,
            },
            {
              time_epoch: 1653094800,
              time: "2022-05-21 02:00",
              temp_c: 10.6,
              temp_f: 51.1,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 251,
              wind_dir: "WSW",
              pressure_mb: 1021.0,
              pressure_in: 30.14,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 92,
              cloud: 30,
              feelslike_c: 8.8,
              feelslike_f: 47.8,
              windchill_c: 8.8,
              windchill_f: 47.8,
              heatindex_c: 10.6,
              heatindex_f: 51.1,
              dewpoint_c: 9.3,
              dewpoint_f: 48.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 1.0,
            },
            {
              time_epoch: 1653098400,
              time: "2022-05-21 03:00",
              temp_c: 10.0,
              temp_f: 50.0,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 8.1,
              wind_kph: 13.0,
              wind_degree: 242,
              wind_dir: "WSW",
              pressure_mb: 1021.0,
              pressure_in: 30.15,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 92,
              cloud: 35,
              feelslike_c: 8.2,
              feelslike_f: 46.8,
              windchill_c: 8.2,
              windchill_f: 46.8,
              heatindex_c: 10.0,
              heatindex_f: 50.0,
              dewpoint_c: 8.8,
              dewpoint_f: 47.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 12.8,
              gust_kph: 20.5,
              uv: 1.0,
            },
            {
              time_epoch: 1653102000,
              time: "2022-05-21 04:00",
              temp_c: 9.5,
              temp_f: 49.1,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 244,
              wind_dir: "WSW",
              pressure_mb: 1021.0,
              pressure_in: 30.15,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 93,
              cloud: 44,
              feelslike_c: 7.7,
              feelslike_f: 45.9,
              windchill_c: 7.7,
              windchill_f: 45.9,
              heatindex_c: 9.5,
              heatindex_f: 49.1,
              dewpoint_c: 8.4,
              dewpoint_f: 47.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 11.9,
              gust_kph: 19.1,
              uv: 1.0,
            },
            {
              time_epoch: 1653105600,
              time: "2022-05-21 05:00",
              temp_c: 9.7,
              temp_f: 49.5,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 249,
              wind_dir: "WSW",
              pressure_mb: 1021.0,
              pressure_in: 30.16,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 92,
              cloud: 43,
              feelslike_c: 8.2,
              feelslike_f: 46.8,
              windchill_c: 8.2,
              windchill_f: 46.8,
              heatindex_c: 9.7,
              heatindex_f: 49.5,
              dewpoint_c: 8.4,
              dewpoint_f: 47.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 1.0,
            },
            {
              time_epoch: 1653109200,
              time: "2022-05-21 06:00",
              temp_c: 10.6,
              temp_f: 51.1,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 252,
              wind_dir: "WSW",
              pressure_mb: 1022.0,
              pressure_in: 30.16,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 86,
              cloud: 36,
              feelslike_c: 9.1,
              feelslike_f: 48.4,
              windchill_c: 9.1,
              windchill_f: 48.4,
              heatindex_c: 10.6,
              heatindex_f: 51.1,
              dewpoint_c: 8.4,
              dewpoint_f: 47.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 4.0,
            },
            {
              time_epoch: 1653112800,
              time: "2022-05-21 07:00",
              temp_c: 12.2,
              temp_f: 54.0,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 253,
              wind_dir: "WSW",
              pressure_mb: 1022.0,
              pressure_in: 30.18,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 78,
              cloud: 100,
              feelslike_c: 10.9,
              feelslike_f: 51.6,
              windchill_c: 10.9,
              windchill_f: 51.6,
              heatindex_c: 12.2,
              heatindex_f: 54.0,
              dewpoint_c: 8.5,
              dewpoint_f: 47.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 3.0,
            },
            {
              time_epoch: 1653116400,
              time: "2022-05-21 08:00",
              temp_c: 13.6,
              temp_f: 56.5,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 247,
              wind_dir: "WSW",
              pressure_mb: 1022.0,
              pressure_in: 30.18,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 71,
              cloud: 56,
              feelslike_c: 12.6,
              feelslike_f: 54.7,
              windchill_c: 12.6,
              windchill_f: 54.7,
              heatindex_c: 13.6,
              heatindex_f: 56.5,
              dewpoint_c: 8.4,
              dewpoint_f: 47.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 4.0,
            },
            {
              time_epoch: 1653120000,
              time: "2022-05-21 09:00",
              temp_c: 14.9,
              temp_f: 58.8,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 247,
              wind_dir: "WSW",
              pressure_mb: 1022.0,
              pressure_in: 30.17,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 63,
              cloud: 40,
              feelslike_c: 14.1,
              feelslike_f: 57.4,
              windchill_c: 14.1,
              windchill_f: 57.4,
              heatindex_c: 14.9,
              heatindex_f: 58.8,
              dewpoint_c: 8.0,
              dewpoint_f: 46.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 4.0,
            },
            {
              time_epoch: 1653123600,
              time: "2022-05-21 10:00",
              temp_c: 16.0,
              temp_f: 60.8,
              is_day: 1,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                code: 1006,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 247,
              wind_dir: "WSW",
              pressure_mb: 1022.0,
              pressure_in: 30.17,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 56,
              cloud: 84,
              feelslike_c: 16.0,
              feelslike_f: 60.8,
              windchill_c: 16.0,
              windchill_f: 60.8,
              heatindex_c: 16.0,
              heatindex_f: 60.8,
              dewpoint_c: 7.2,
              dewpoint_f: 45.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 4.0,
            },
            {
              time_epoch: 1653127200,
              time: "2022-05-21 11:00",
              temp_c: 16.7,
              temp_f: 62.1,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 255,
              wind_dir: "WSW",
              pressure_mb: 1022.0,
              pressure_in: 30.16,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 52,
              cloud: 53,
              feelslike_c: 16.7,
              feelslike_f: 62.1,
              windchill_c: 16.7,
              windchill_f: 62.1,
              heatindex_c: 16.7,
              heatindex_f: 62.1,
              dewpoint_c: 6.7,
              dewpoint_f: 44.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 5.0,
            },
            {
              time_epoch: 1653130800,
              time: "2022-05-21 12:00",
              temp_c: 16.9,
              temp_f: 62.4,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 253,
              wind_dir: "WSW",
              pressure_mb: 1021.0,
              pressure_in: 30.16,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 50,
              cloud: 49,
              feelslike_c: 16.9,
              feelslike_f: 62.4,
              windchill_c: 16.9,
              windchill_f: 62.4,
              heatindex_c: 16.9,
              heatindex_f: 62.4,
              dewpoint_c: 6.5,
              dewpoint_f: 43.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 5.0,
            },
            {
              time_epoch: 1653134400,
              time: "2022-05-21 13:00",
              temp_c: 18.1,
              temp_f: 64.6,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 8.7,
              wind_kph: 14.0,
              wind_degree: 259,
              wind_dir: "W",
              pressure_mb: 1021.0,
              pressure_in: 30.16,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 47,
              cloud: 46,
              feelslike_c: 18.1,
              feelslike_f: 64.6,
              windchill_c: 18.1,
              windchill_f: 64.6,
              heatindex_c: 18.1,
              heatindex_f: 64.6,
              dewpoint_c: 6.5,
              dewpoint_f: 43.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 5.0,
            },
            {
              time_epoch: 1653138000,
              time: "2022-05-21 14:00",
              temp_c: 18.7,
              temp_f: 65.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 257,
              wind_dir: "WSW",
              pressure_mb: 1021.0,
              pressure_in: 30.15,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 45,
              cloud: 25,
              feelslike_c: 18.7,
              feelslike_f: 65.7,
              windchill_c: 18.7,
              windchill_f: 65.7,
              heatindex_c: 18.7,
              heatindex_f: 65.7,
              dewpoint_c: 6.4,
              dewpoint_f: 43.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 5.0,
            },
            {
              time_epoch: 1653141600,
              time: "2022-05-21 15:00",
              temp_c: 19.1,
              temp_f: 66.4,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 8.7,
              wind_kph: 14.0,
              wind_degree: 257,
              wind_dir: "WSW",
              pressure_mb: 1021.0,
              pressure_in: 30.14,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 44,
              cloud: 29,
              feelslike_c: 19.1,
              feelslike_f: 66.4,
              windchill_c: 19.1,
              windchill_f: 66.4,
              heatindex_c: 19.1,
              heatindex_f: 66.4,
              dewpoint_c: 6.6,
              dewpoint_f: 43.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 5.0,
            },
            {
              time_epoch: 1653145200,
              time: "2022-05-21 16:00",
              temp_c: 18.3,
              temp_f: 64.9,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 268,
              wind_dir: "W",
              pressure_mb: 1020.0,
              pressure_in: 30.13,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 47,
              cloud: 53,
              feelslike_c: 18.3,
              feelslike_f: 64.9,
              windchill_c: 18.3,
              windchill_f: 64.9,
              heatindex_c: 18.3,
              heatindex_f: 64.9,
              dewpoint_c: 6.8,
              dewpoint_f: 44.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.6,
              gust_kph: 15.5,
              uv: 5.0,
            },
            {
              time_epoch: 1653148800,
              time: "2022-05-21 17:00",
              temp_c: 17.9,
              temp_f: 64.2,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 275,
              wind_dir: "W",
              pressure_mb: 1020.0,
              pressure_in: 30.12,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 52,
              cloud: 29,
              feelslike_c: 17.9,
              feelslike_f: 64.2,
              windchill_c: 17.9,
              windchill_f: 64.2,
              heatindex_c: 17.9,
              heatindex_f: 64.2,
              dewpoint_c: 7.9,
              dewpoint_f: 46.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.6,
              gust_kph: 12.2,
              uv: 5.0,
            },
            {
              time_epoch: 1653152400,
              time: "2022-05-21 18:00",
              temp_c: 17.5,
              temp_f: 63.5,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 289,
              wind_dir: "WNW",
              pressure_mb: 1020.0,
              pressure_in: 30.12,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 56,
              cloud: 56,
              feelslike_c: 17.5,
              feelslike_f: 63.5,
              windchill_c: 17.5,
              windchill_f: 63.5,
              heatindex_c: 17.5,
              heatindex_f: 63.5,
              dewpoint_c: 8.6,
              dewpoint_f: 47.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 5.0,
            },
            {
              time_epoch: 1653156000,
              time: "2022-05-21 19:00",
              temp_c: 16.9,
              temp_f: 62.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.0,
              wind_kph: 6.5,
              wind_degree: 306,
              wind_dir: "NW",
              pressure_mb: 1020.0,
              pressure_in: 30.13,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 63,
              cloud: 16,
              feelslike_c: 16.9,
              feelslike_f: 62.4,
              windchill_c: 16.9,
              windchill_f: 62.4,
              heatindex_c: 16.9,
              heatindex_f: 62.4,
              dewpoint_c: 9.8,
              dewpoint_f: 49.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.9,
              gust_kph: 7.9,
              uv: 5.0,
            },
            {
              time_epoch: 1653159600,
              time: "2022-05-21 20:00",
              temp_c: 14.3,
              temp_f: 57.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2.9,
              wind_kph: 4.7,
              wind_degree: 305,
              wind_dir: "NW",
              pressure_mb: 1020.0,
              pressure_in: 30.13,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 68,
              cloud: 16,
              feelslike_c: 14.7,
              feelslike_f: 58.5,
              windchill_c: 14.7,
              windchill_f: 58.5,
              heatindex_c: 14.3,
              heatindex_f: 57.7,
              dewpoint_c: 8.6,
              dewpoint_f: 47.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.9,
              gust_kph: 7.9,
              uv: 4.0,
            },
            {
              time_epoch: 1653163200,
              time: "2022-05-21 21:00",
              temp_c: 13.7,
              temp_f: 56.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.0,
              wind_kph: 3.2,
              wind_degree: 288,
              wind_dir: "WNW",
              pressure_mb: 1020.0,
              pressure_in: 30.13,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 71,
              cloud: 19,
              feelslike_c: 14.5,
              feelslike_f: 58.1,
              windchill_c: 14.5,
              windchill_f: 58.1,
              heatindex_c: 13.7,
              heatindex_f: 56.7,
              dewpoint_c: 8.6,
              dewpoint_f: 47.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 3.4,
              gust_kph: 5.4,
              uv: 1.0,
            },
            {
              time_epoch: 1653166800,
              time: "2022-05-21 22:00",
              temp_c: 13.1,
              temp_f: 55.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.2,
              wind_kph: 3.6,
              wind_degree: 286,
              wind_dir: "WNW",
              pressure_mb: 1020.0,
              pressure_in: 30.12,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 73,
              cloud: 23,
              feelslike_c: 13.7,
              feelslike_f: 56.7,
              windchill_c: 13.7,
              windchill_f: 56.7,
              heatindex_c: 13.1,
              heatindex_f: 55.6,
              dewpoint_c: 8.4,
              dewpoint_f: 47.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.0,
              gust_kph: 6.5,
              uv: 1.0,
            },
            {
              time_epoch: 1653170400,
              time: "2022-05-21 23:00",
              temp_c: 12.9,
              temp_f: 55.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 1.3,
              wind_kph: 2.2,
              wind_degree: 261,
              wind_dir: "W",
              pressure_mb: 1020.0,
              pressure_in: 30.12,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 75,
              cloud: 15,
              feelslike_c: 12.9,
              feelslike_f: 55.2,
              windchill_c: 12.9,
              windchill_f: 55.2,
              heatindex_c: 12.9,
              heatindex_f: 55.2,
              dewpoint_c: 8.6,
              dewpoint_f: 47.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 2.2,
              gust_kph: 3.6,
              uv: 1.0,
            },
          ],
        },
      ],
    },
  },
  dayLoadFlag: false, 
  dayLoadData: {},
  showSearchFlag: false,
  // responseFlag: false,
  loading: false,
  error: null,
};

function reducer(state = initialState, action) {
  switch (action.type) {
    case GET_DATA_REQUEST:
      return {
        ...state,
        loading: true,
      };
    case GET_DATA_SUCCESS:
      return {
        ...state,
        response: action.payload.data,
        loading: false,
      };
    case GET_DATA_FAILURE:
      return {
        ...state,
        error: action.payload.error,
        loading: false,
      };
    case GO_TO_FORECAST:
      return {
        ...state,
        dayLoadFlag: true,
        dayLoadData: action.payload.forecastData,
      };
    case BACK_TO_CURRENT:
      return {
        ...state,
        dayLoadFlag: false,
        dayLoadData: {},
      };
    case SHOW_SEARCH_BOX:
      return {
        ...state,
        showSearchFlag: true,
      };
    case HIDE_SEARCH_BOX:
      return {
        ...state,
        showSearchFlag: false,
      };
    default:
      return state;
  }
}

export default reducer;
