export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";
export const GO_TO_FORECAST = "GO_TO_FORECAST";
export const BACK_TO_CURRENT = "BACK_TO_CURRENT";
export const SHOW_SEARCH_BOX = "SHOW_SEARCH_BOX";
export const HIDE_SEARCH_BOX = "HIDE_SEARCH_BOX";
